from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    #moh
    path('moh/dashboard/', views.moh_dashboard, name='moh_dashboard'),
    path('moh/notices/', views.moh_notices, name='moh_notices'),
    # Notices
path('moh/notices/', views.moh_notices, name='moh_notices'),
path('moh/notices/create/', views.moh_notice_create, name='moh_notice_create'),
path('moh/notices/<int:pk>/', views.moh_notice_view, name='moh_notice_view'),
path('moh/notices/<int:pk>/edit/', views.moh_notice_edit, name='moh_notice_edit'),
path('moh/notices/<int:pk>/delete/', views.moh_notice_delete, name='moh_notice_delete'),
    path('moh/hospital-approval/', views.hospital_approval, name='hospital_approval'),
    path('moh/facilities/', views.moh_facilities, name='moh_facilities'),
    path('moh/analytics/', views.moh_analytics, name='moh_analytics'),
    path('moh/configuration/', views.moh_configuration, name='moh_configuration'),
    path('moh/notifications/', views.moh_notifications, name='moh_notifications'),
    #hospital admin urls
path('hospital-admin/', views.hospital_admin_dashboard, name='hospital_admin_dashboard'),
path('moh/notifications/', views.moh_notifications, name='moh_notifications'),
path('hospital-admin/', views.hospital_admin_dashboard, name='hospital_admin_dashboard'),
path('hospital-admin/notices/', views.hospital_admin_notices, name='hospital_admin_notices'),
path('hospital-admin/doctors/', views.hospital_doctors, name='hospital_doctors'),
path('hospital-admin/staff/', views.hospital_staff, name='hospital_staff'),
path('hospital-admin/profile/', views.hospital_profile, name='hospital_profile'),
path('hospital-admin/departments/', views.hospital_departments, name='hospital_departments'),
path('hospital-admin/patients/', views.hospital_patients, name='hospital_patients'),
path('hospital-admin/documents/', views.hospital_documents, name='hospital_documents'),
path('hospital-admin/payroll/', views.hospital_payroll, name='hospital_payroll'),
path('hospital-admin/pharmacy/', views.hospital_pharmacy, name='hospital_pharmacy'),
path('hospital-admin/blood-bank/', views.hospital_blood_bank, name='hospital_blood_bank'),
path('hospital-admin/diagnostics/', views.hospital_diagnostics, name='hospital_diagnostics'),
path('hospital-admin/users-access/', views.hospital_users_access, name='hospital_users_access'),
path('hospital-admin/facility/', views.hospital_facility, name='hospital_facility'),
path('hospital-admin/settings/', views.hospital_admin_settings, name='hospital_admin_settings'),
path('hospital-admin/contact-support/', views.hospital_contact_support, name='hospital_contact_support'),
path('hospital-admin/notifications/', views.hospital_notifications, name='hospital_notifications'),
#doctors
path('doctor/', views.doctor_dashboard, name='doctor_dashboard'),
path('doctor/patient-summary/', views.doctor_patient_summary, name='doctor_patient_summary'),
path('doctor/prescription/', views.doctor_prescription, name='doctor_prescription'),
path('doctor/referrals/', views.doctor_referrals, name='doctor_referrals'),
path('doctor/appointments/', views.doctor_appointments, name='doctor_appointments'),
path('doctor/admissions/', views.doctor_admissions, name='doctor_admissions'),
path('doctor/schedule/', views.doctor_schedule, name='doctor_schedule'),
path('doctor/profile/', views.doctor_profile, name='doctor_profile'),
#nourse
path('nurse/dashboard/', views.nurse_dashboard, name='nurse_dashboard'),
path('nurse/vital-signs/', views.nurse_vital_signs, name='nurse_vital_signs'),
path('nurse/nursing-notes/', views.nurse_notes, name='nurse_notes'),
path('nurse/patients/', views.nurse_patients, name='nurse_patients'),
path('nurse/notifications/', views.nurse_notifications, name='nurse_notifications'),
path('nurse/profile/', views.nurse_profile, name='nurse_profile'),
#patient
path('patient/dashboard/', views.patient_dashboard, name='patient_dashboard'),
path('patient/notices/', views.patient_notices, name='patient_notices'),
path('patient/departments/', views.patient_departments, name='patient_departments'),
path('patient/doctors/', views.patient_doctors, name='patient_doctors'),
path('patient/appointments/', views.patient_appointments, name='patient_appointments'),
path('patient/medical-records/', views.patient_medical_records, name='patient_medical_records'),
path('patient/payments/', views.patient_payments, name='patient_payments'),
path('patient/emergency-contact/', views.patient_emergency_contact, name='patient_emergency_contact'),
path('patient/profile/', views.patient_profile, name='patient_profile'),
#diagnostic lab
path('lab/dashboard/', views.lab_dashboard, name='lab_dashboard'),
path('lab/upload-report/', views.lab_upload_report, name='lab_upload_report'),
path('lab/report-status/', views.lab_report_status, name='lab_report_status'),
path('lab/report-preview/', views.lab_report_preview, name='lab_report_preview'),
path('lab/history/', views.lab_history, name='lab_history'),
path('lab/profile/', views.lab_profile, name='lab_profile'),
#counter
path('counter/dashboard/', views.counter_dashboard, name='counter_dashboard'),
path('counter/patients/', views.counter_patients, name='counter_patients'),
path('counter/appointments/', views.counter_appointments, name='counter_appointments'),
path('counter/doctors/', views.counter_doctors, name='counter_doctors'),
path('counter/billing/', views.counter_billing, name='counter_billing'),
path('counter/notices/', views.counter_notices, name='counter_notices'),
path('counter/profile/', views.counter_profile, name='counter_profile'),
#blood bank
path('bloodbank/dashboard/', views.bloodbank_dashboard, name='bloodbank_dashboard'),
path('bloodbank/donors/', views.bloodbank_donors, name='bloodbank_donors'),
path('bloodbank/inventory/', views.bloodbank_inventory, name='bloodbank_inventory'),
path('bloodbank/requests/', views.bloodbank_requests, name='bloodbank_requests'),
path('bloodbank/collection/', views.bloodbank_collection, name='bloodbank_collection'),
path('bloodbank/testing/', views.bloodbank_testing, name='bloodbank_testing'),
path('bloodbank/issue/', views.bloodbank_issue, name='bloodbank_issue'),
path('bloodbank/notices/', views.bloodbank_notices, name='bloodbank_notices'),
path('bloodbank/profile/', views.bloodbank_profile, name='bloodbank_profile'),
# accountant
path('accountant/dashboard/', views.accountant_dashboard, name='accountant_dashboard'),
path('accountant/billing/', views.accountant_billing, name='accountant_billing'),
path('accountant/payments/', views.accountant_payments, name='accountant_payments'),
path('accountant/invoices/', views.accountant_invoices, name='accountant_invoices'),
path('accountant/expenses/', views.accountant_expenses, name='accountant_expenses'),
path('accountant/payroll/', views.accountant_payroll, name='accountant_payroll'),
path('accountant/accounts/', views.accountant_accounts, name='accountant_accounts'),
path('accountant/reports/', views.accountant_reports, name='accountant_reports'),
path('accountant/notices/', views.accountant_notices, name='accountant_notices'),
path('accountant/notifications/', views.accountant_notifications, name='accountant_notifications'),
path('accountant/profile/', views.accountant_profile, name='accountant_profile'),
]