# Generated by Django 5.2.17 on 2026-10-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='license',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
