# Generated by Django 5.2.17 on 2026-10-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
