# Generated by Django 5.2.17 on 2026-10-01 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='target_hospital',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='target_role',
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('general', 'General'), ('announcement', 'Announcement'), ('alert', 'Alert'), ('maintenance', 'Maintenance'), ('policy', 'Policy Update')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
    ]
