# Generated by Django 5.2.17 on 2026-10-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_message_notice_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('visits', models.PositiveIntegerField(default=0)),
                ('reports', models.PositiveIntegerField(default=0)),
                ('prescriptions', models.PositiveIntegerField(default=0)),
                ('respiratory', models.PositiveIntegerField(default=0)),
                ('diabetes', models.PositiveIntegerField(default=0)),
                ('cardiac', models.PositiveIntegerField(default=0)),
                ('dermatology', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
    ]
