# Generated by Django 5.2.17 on 2026-10-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_monthlystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='NHIMS', max_length=255)),
                ('company_email', models.EmailField(default='info@nhims.gov.bd', max_length=254)),
                ('phone', models.CharField(blank=True, default='+880', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('timezone', models.CharField(choices=[('Asia/Dhaka', 'Asia/Dhaka (GMT+6)'), ('UTC', 'UTC'), ('Asia/Kolkata', 'Asia/Kolkata (GMT+5:30)'), ('Asia/Karachi', 'Asia/Karachi (GMT+5)')], default='Asia/Dhaka', max_length=50)),
                ('currency', models.CharField(choices=[('BDT', 'BDT (৳)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('INR', 'INR (₹)')], default='BDT', max_length=10)),
                ('date_format', models.CharField(choices=[('DD-MM-YYYY', 'DD-MM-YYYY'), ('MM-DD-YYYY', 'MM-DD-YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD-MM-YYYY', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.DeleteModel(
            name='MonthlyStat',
        ),
    ]
