# Generated by Django 5.2.17 on 2026-10-04 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notice_hospital'),
        ('hospitals', '0002_hospital_city_hospital_facility_type_hospital_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('emergency', 'Emergency'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology & Obstetrics'), ('medicine', 'Internal Medicine'), ('surgery', 'General Surgery'), ('dermatology', 'Dermatology'), ('ent', 'ENT'), ('ophthalmology', 'Ophthalmology'), ('psychiatry', 'Psychiatry'), ('oncology', 'Oncology'), ('urology', 'Urology'), ('nephrology', 'Nephrology'), ('gastroenterology', 'Gastroenterology'), ('radiology', 'Radiology'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('blood_bank', 'Blood Bank'), ('icu', 'ICU'), ('nicu', 'NICU'), ('ccu', 'CCU'), ('physiotherapy', 'Physiotherapy'), ('dental', 'Dental'), ('medical_records', 'Medical Records'), ('administration', 'Administration')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('hospital', 'name'), name='unique_department_per_hospital')],
            },
        ),
    ]
