# Generated by Django 5.2.17 on 2026-10-04 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_systemsettings_logo'),
        ('hospitals', '0002_hospital_city_hospital_facility_type_hospital_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='logo',
        ),
        migrations.CreateModel(
            name='HospitalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='hospital_documents/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_documents', to='hospitals.hospital')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
