# Generated by Django 5.2.17 on 2026-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moh', 'Ministry of Health (MOH)'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('patient', 'Patient'), ('lab', 'Laboratory / Diagnostic'), ('counter', 'Counter / Reception'), ('bloodbank', 'Blood Bank Staff'), ('accountant', 'Accountant'), ('pharmacy', 'Pharmacy')], max_length=20),
        ),
    ]
