# Generated by Django 5.2.17 on 2026-10-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_medicine'),
        ('hospitals', '0002_hospital_city_hospital_facility_type_hospital_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('component', models.CharField(choices=[('whole', 'Whole Blood'), ('rbc', 'Red Blood Cells'), ('plasma', 'Plasma'), ('platelets', 'Platelets'), ('cryo', 'Cryoprecipitate')], default='whole', max_length=20)),
                ('units', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('bag_number', models.CharField(blank=True, max_length=50)),
                ('donor_name', models.CharField(blank=True, max_length=100)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_units', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['blood_group', 'component'],
            },
        ),
    ]
