# Generated by Django 5.2.17 on 2026-10-08 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_blood'),
        ('hospitals', '0002_hospital_city_hospital_facility_type_hospital_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('blood', 'Blood Test'), ('urine', 'Urine Test'), ('imaging', 'Imaging'), ('pathology', 'Pathology'), ('microbiology', 'Microbiology'), ('cardiology', 'Cardiology'), ('other', 'Other')], default='blood', max_length=30)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('swab', 'Swab'), ('tissue', 'Tissue'), ('none', 'None')], default='blood', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('report_time', models.CharField(blank=True, help_text='e.g. 24 hours, 2 days', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_tests', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
