# Generated by Django 5.2.17 on 2026-10-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_diagnostictest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_bank_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='diagnostics_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='patients_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_access',
            field=models.BooleanField(default=False),
        ),
    ]
