# Generated by Django 5.2.17 on 2026-10-08 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_blood_bank_access_user_diagnostics_access_and_more'),
        ('hospitals', '0002_hospital_city_hospital_facility_type_hospital_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(choices=[('ward', 'Ward'), ('icu', 'ICU'), ('ot', 'Operation Theater'), ('lab', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('blood_bank', 'Blood Bank'), ('emergency', 'Emergency'), ('opd', 'OPD'), ('radiology', 'Radiology'), ('other', 'Other')], default='ward', max_length=30)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Beds / Units')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='hospitals.hospital')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(choices=[('ward', 'Ward'), ('icu', 'ICU'), ('ot', 'Operation Theater'), ('lab', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('blood_bank', 'Blood Bank'), ('emergency', 'Emergency'), ('opd', 'OPD'), ('radiology', 'Radiology'), ('other', 'Other')], max_length=30)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(help_text='Why this facility is needed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('moh_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_requests', to='hospitals.hospital')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
