# Generated by Django 5.2.17 on 2026-10-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_facility_facilityrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facilityrequest',
            name='reason',
            field=models.TextField(),
        ),
    ]
