# Generated by Django 5.2.17 on 2026-10-09 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_doctorprofile'),
        ('hospitals', '0002_hospital_city_hospital_facility_type_hospital_state'),
        ('patients', '0002_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80', max_length=20)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='breaths/min', null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, help_text='%', null=True)),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=1, help_text='mg/dL', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='kg', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
