# Generated by Django 5.2.17 on 2026-10-10 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_patientappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
