# Generated by Django 5.2.17 on 2026-10-11 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_patientappointment_doctor'),
        ('hospitals', '0002_hospital_city_hospital_facility_type_hospital_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_id', models.CharField(blank=True, max_length=50)),
                ('patient_phone', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('record_type', models.CharField(choices=[('lab', 'Lab Report'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('discharge', 'Discharge Summary'), ('other', 'Other')], default='lab', max_length=30)),
                ('test_name', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(upload_to='medical_records/')),
                ('notes', models.TextField(blank=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='hospitals.hospital')),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
