# Generated by Django 5.2.17 on 2026-10-11 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_patientemergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('nid', models.CharField(blank=True, help_text='National ID', max_length=30)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('emergency_name', models.CharField(blank=True, max_length=150)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='patient_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_account_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
