# Generated by Django 5.2.17 on 2026-10-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='facility_type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('lab', 'Lab'), ('specialty', 'Specialty')], default='hospital', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
